[package]
name = "juno_ast"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "MIT"

[dependencies]
juno_support = { path = "../juno_support" }
libc = "0.2"
memoffset = "0.6.1"
thiserror = "1.0"
