version: 2
updates:
- package-ecosystem: npm
  directories:
  - "/"
  - "/.ado/scripts"
  - "/benchmarks/build-helpers/flow-bundler"
  - "/benchmarks/raytracer/original"
  - "/tools/fork-sync"
  - "/tools/hcdp"
  - "/tools/hermes-parser/js"
  - "/unittests/NodeApi/test"
  - "/utils/promise"
  - "/utils/scripts/hermes"
  schedule:
    interval: daily
    time: "05:00"
    timezone: "America/Los_Angeles"
  labels:
  - dependencies
  versioning-strategy: lockfile-only
  commit-message:
    prefix: 📦
  open-pull-requests-limit: 5
  groups:
    all-npm-dependencies:
      patterns:
      - "*"
