/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// REQUIRES: napi
// UNSUPPORTED: windows

// RUN: echo 'var addon = loadNativeModule("%napi_addon_dir/napi_test_addon.node"); print(typeof addon); print(addon.hello); print(typeof loadNativeModule);' > %t.js && %hermes %t.js | %FileCheck --match-full-lines %s

// CHECK: object
// CHECK-NEXT: world
// CHECK-NEXT: function
