[package]
name = "support"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "MIT"

[dependencies]
base64 = "0.13"
anyhow = "1.0"
thiserror = "1.0"
url = "2.2.2"

[build-dependencies]
toml = "=0.5.7"
