[package]
name = "hermes"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "MIT"

[dependencies]
juno_support = { path = "../juno_support" }
libcplusplus = { path = "../libcplusplus" }
libc = "0.2"
thiserror = "1.0"

[build-dependencies]
cmake = "0.1"
