[package]
name = "flow_native"
version = "0.1.0"
authors = ["Facebook"]
edition = "2018"
license = "MIT"

[[bin]]
name = "fnc"
path = "src/main.rs"

[dependencies]
juno = { path = "../juno" }
juno_support = { path = "../juno_support" }
juno_pass = { path = "../juno_pass" }
command_line = { path = "../command_line" }
anyhow = "1.0"

[dev-dependencies]
assert_cmd = "0.12"
toml = "=0.5.7"
lit = { path = "../lit" }
