name: build-hermesc-windows

on:
  workflow_call

jobs:
  build-hermesc-windows:
    runs-on: windows-2025
    env:
      HERMES_WS_DIR: 'C:\tmp\hermes'
      HERMES_TARBALL_ARTIFACTS_DIR: 'C:\tmp\hermes\hermes-runtime-darwin'
      HERMES_OSXBIN_ARTIFACTS_DIR: 'C:\tmp\hermes\osx-bin'
      ICU_URL: "https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-Win64-MSVC2017.zip"
      MSBUILD_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin'
      CMAKE_DIR: 'C:\Program Files\CMake\bin'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up workspace
        shell: powershell
        run: |
          mkdir -p C:\tmp\hermes\osx-bin
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.3.2
      - name: Set up workspace
        shell: powershell
        run: |
          New-Item -ItemType Directory -ErrorAction SilentlyContinue $Env:HERMES_WS_DIR\icu
          New-Item -ItemType Directory -ErrorAction SilentlyContinue $Env:HERMES_WS_DIR\deps
          New-Item -ItemType Directory -ErrorAction SilentlyContinue $Env:HERMES_WS_DIR\win64-bin
      - name: Downgrade CMake
        shell: powershell
        run: choco install cmake --version 3.31.6 --force
      - name: Build HermesC for Windows
        shell: powershell
        run: |
          cd $Env:HERMES_WS_DIR\icu
          # If Invoke-WebRequest shows a progress bar, it will fail with
          #   Win32 internal error "Access is denied" 0x5 occurred [...]
          $progressPreference = 'silentlyContinue'
          Invoke-WebRequest -Uri "$Env:ICU_URL" -OutFile "icu.zip"
          Expand-Archive -Path "icu.zip" -DestinationPath "."

          cd $Env:HERMES_WS_DIR
          Copy-Item -Path "icu\bin64\icu*.dll" -Destination "deps"
          # Include MSVC++ 2015 redistributables
          Copy-Item -Path "c:\windows\system32\msvcp140.dll" -Destination "deps"
          Copy-Item -Path "c:\windows\system32\vcruntime140.dll" -Destination "deps"
          Copy-Item -Path "c:\windows\system32\vcruntime140_1.dll" -Destination "deps"

          $Env:PATH += ";$Env:CMAKE_DIR;$Env:MSBUILD_DIR"
          $Env:ICU_ROOT = "$Env:HERMES_WS_DIR\icu"

          cd $Env:GITHUB_WORKSPACE
          cmake -S . -B build_release -G 'Visual Studio 17 2022' -Ax64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=True -DHERMES_ENABLE_WIN10_ICU_FALLBACK=OFF
          if (-not $?) { throw "Failed to configure Hermes" }
          echo "Running windows build..."
          cd build_release
          cmake --build . --target hermesc --config Release
          if (-not $?) { throw "Failed to build Hermes" }

          echo "Copying hermesc.exe to win64-bin"
          cd $Env:GITHUB_WORKSPACE
          Copy-Item -Path "build_release\bin\Release\hermesc.exe" -Destination "$Env:HERMES_WS_DIR\win64-bin"
          # Include Windows runtime dependencies
          Copy-Item -Path "$Env:HERMES_WS_DIR\deps\*" -Destination "$Env:HERMES_WS_DIR\win64-bin"
      - name: Upload windows artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: hermes-win64-bin
          path: C:\tmp\hermes\win64-bin\
