name: Build Hermes

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_hermesc_apple:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build HermesC Apple
        uses: ./.github/actions/build-hermesc-apple
