name: test-apple-runtime

on:
  workflow_call

jobs:
  test-apple-runtime:
    runs-on: macos-14
    env:
      TERM: dumb
      HERMES_WS_DIR: "/tmp/hermes"
      HOMEBREW_NO_AUTO_UPDATE: 1
    strategy:
      matrix:
        include:
          - destination: platform=macOS
            scheme: ApplePlatformsIntegrationMacTests
            name: Test MacOS application
          - destination: platform=iOS Simulator,name=iPhone 16
            scheme: ApplePlatformsIntegrationMobileTests
            name: Test iPhone application
          - destination: platform=visionOS Simulator,name=Apple Vision Pro
            scheme: ApplePlatformsIntegrationVisionOSTests
            name: Test Apple Vision application
          - destination: platform=tvOS Simulator,name=Apple TV
            scheme: ApplePlatformsIntegrationTVOSTests
            name: Test Apple TV application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup xcode
        uses: ./.github/actions/setup-xcode
      - name: Install dependencies
        shell: bash
        run: brew install cmake ninja
      - name: Download visionOS SDK
        shell: bash
        if: ${{ matrix.scheme == 'ApplePlatformsIntegrationVisionOSTests' }}
        run: xcodebuild -downloadPlatform visionOS
      - name: Download tvOS SDK
        shell: bash
        if: ${{ matrix.scheme == 'ApplePlatformsIntegrationTVOSTests' }}
        run: xcodebuild -downloadPlatform tvOS
      - name: Use built artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
          name: hermes-darwin-bin-Debug
      - name: Unzip artifacts
        shell: bash
        run: |
          ls -l .
          tar -xzv -f hermes-ios-Debug.tar.gz
      - name: Run pod install on ApplePlatformsIntegrationTestApp
        shell: bash
        run: pod install
        working-directory: test/ApplePlatformsIntegrationTestApp
      - name: ${{ matrix.name }}
        shell: bash
        run: |-
          xcodebuild test \
            -workspace ApplePlatformsIntegrationTests.xcworkspace \
            -configuration Debug \
            -destination '${{ matrix.destination }}' \
            -scheme ${{ matrix.scheme }}
        working-directory: test/ApplePlatformsIntegrationTestApp
